### PR TITLE
Update dependencies and fix build error

### LINKED ISSUE #46: loadData problem with ReadableStream
Slightly odd bug to report that might be me simply misusing this (great!) library. In nodejs 0.10.33 everything works great, but in the latest nodejs (0.12.4) I am seeing an error when using jBinary.loadData in conjunction with a ReadableStream 

```
buffer.js:201
  length += list[i].length;
                   ^
TypeError: Cannot read property 'length' of null
    at Function.Buffer.concat (buffer.js:201:24)
    at PassThrough.<anonymous> (.....\node_modules\jbinary\dist\node\jbinary.js:451:39)
    at PassThrough.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickDomainCallback (node.js:381:11)
```

I'm using nodejs v0.12.4 and the 'async' library. Here is the offending code:

```
async.waterfall([
     var stream = require('fs').createReadStream('path/to/file');
     next(null, stream);
},
function parseFile(stream, next) {
  jBinary.loadData(stream, MY_TYPESET_HERE, function(err, binary) {
      // execution does not get this far
      var myData = jbinary.readAll();
  });
},
```

jBinary.loadData basically blows up when I pass a readableStream to it. I'm very new to nodejs so I'm not sure what the issue is, but presumably nodejs' ReadableStream has changed from node 0.10.x -> 0.12.x and maybe jBinary does not officially support ReadableStream as a data source?  Is this even an issue in jBinary to start with?

This code fragment is actually part of a much larger project that uses AWS's S3 storage API. I'm retrieving the file from an S3 bucket and not simply using a static file. I can work around this issue by either downloading the file to temp storage and then loading it that way (and avoiding use of ReadbleStream), or avoiding storing the S3 file to disk entirely, and keeping everything in-memory Buffer. 

As an aside, what is jBinary's preferred approach to data sources? When loading a file from disk does it load it all into memory anyway, or does it read the file chunk-by-chunk? If the file is always loaded into ram then I guess I can just use Buffers and be done with it

cheers & thanks for a really nice library

### LINKED ISSUE #67: Local build is failing
I cloned the GIT repo and installed the NPM packages using `npm install`.

Then I did this in a command window on Windows:

```sh
C:\MyProjects\code\jBinary>npx grunt
npx: installed 196 in 15.814s
Loading "grunt-karma.js" tasks...ERROR
>> TypeError: Cannot read property 'prototype' of undefined

Running "build" task

Running "newer:lintspaces" (newer) task

Running "newer:lintspaces:all" (newer) task

Running "lintspaces:all" (lintspaces) task
>> 59 lint free.

Running "newer-postrun:lintspaces:all:1:C:\MyProjects\code\jBinary\node_modules\grunt-newer\.cache" (newer-postrun) task

Running "newer:jshint:grunt" (newer) task

Running "jshint:grunt" (jshint) task
Warning: The "path" argument must be of type string. Received null Use --force to continue.

Aborted due to warnings.
```

I've never used Grunt before so maybe `npx grunt` is not what I need to execute?

### PR DESCRIPTION
**Pull request by krisztianb**
This makes the build work again. Closes #67

There are still two packages complaining about incorrect peer dependencies:

```sh
npm WARN grunt-concat-sourcemap@0.4.3 requires a peer of grunt@~0.4.1 but none is installed. You must install peer dependencies yourself.
npm WARN grunt-karma@4.0.0 requires a peer of karma@^4.0.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
```

Unfortunately there is no update for these packages.

I tested the Node.js output locally and it does fix #46 for me. Haven't tested the browser version though. Tests seem to be working. Could you recheck please?

### CODE REVIEW

**Comment by RReverser** [comment]
Thank you. I believe I should be able to get to this next weekend, but, if I forget, please ping me after that 😅

**Comment by krisztianb** [comment]
@RReverser looks like you forgot. 😉

**Comment by RReverser** [comment]
Rather, happened to be busier on the weekend than expected :D I'll try to look at this by the end of this week. Sorry for the delay.

**Comment by RReverser** [comment]
Btw, CI seems to be still failing - can you take a look at why? https://travis-ci.org/github/jDataView/jBinary/builds/766925969

**Comment by krisztianb** [comment]
I haven't worked with Travis before, but a quick search for the error message gave me this solution: https://stackoverflow.com/questions/55674746/travis-sh-0-cant-open-etc-init-d-xvfb

Which seems to have fixed the problem.

**Comment by RReverser** [comment]
I moved grunt-cli to a dev-dependency; otherwise looks great, thanks a lot for fixing this!

**Comment by RReverser** [comment]
Made few more cleanups on CI side (including switching to GH actions) and published as 2.1.5.

It could probably be interesting to refactor this project to ESM and Rollup too as well as remove various polyfills that are no longer necessary in modern browsers, if it's something you want to look into - unfortunately my area of work has slightly changed over years, but I'm happy to accept contributions :)

**Comment by krisztianb** [comment]
Thanks for the new release. 👍

Maybe you could create Issues with the things you would like to (have) changed.

To be honest, I'm currently not interested in binary data related topics. We are using this project to load binary font data that comes from a web service. And as long as it works we are happy with it as it is.

**Comment by RReverser** [comment]
Makes sense, thanks :)

**Pull request merged**
